name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag_name:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag_name || github.ref }}

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install deps
        run: npm i

      - name: Build Chromium version
        run: npm run build:chrome

      - name: Build Firefox version
        run: npm run build:firefox

      - name: Create Chromium archive
        run: |
          mv dist/chrome fairview-chromium
          zip -r fairview-chromium.zip fairview-chromium

      - name: Create Firefox archive
        run: |
          mv dist/firefox fairview-firefox
          zip -r fairview-firefox.zip fairview-firefox

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag_name || github.ref_name }}
          name: ${{ inputs.tag_name || github.ref_name }}
          generate_release_notes: true
          files: |
            fairview-chromium.zip
            fairview-firefox.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
